Repository sherwinokhowat/Group-Formation-System, pull requests merged in 2024-08, with the labels that each got.

#101 Added verification when logging in
  pom.xml
  src/main/java/Main.java
  src/main/java/usecase/createverification/CreateVerificationController.java
  src/main/java/usecase/createverification/CreateVerificationInputBoundary.java
  src/main/java/usecase/createverification/CreateVerificationInteractor.java
  src/main/java/usecase/createverification/CreateVerificationOutputBoundary.java
  src/main/java/usecase/createverification/CreateVerificationOutputData.java
  src/main/java/usecase/createverification/CreateVerificationPresenter.java
  src/main/java/usecase/createverification/CreateVerificationUseCaseFactory.java
  src/main/java/usecase/createverification/CreateVerificationViewModel.java
  src/main/java/usecase/createverification/ImageFinder.java
  src/main/java/usecase/createverification/ImageFinderInterface.java
  src/main/java/view/LoginPanel.java
  src/main/java/view/LoginVerificationView.java
  src/main/java/view/components/ImagePanel.java
  src/main/java/viewmodel/LoginVerificationViewModel.java
  verifyimages/cat1.jpg
  verifyimages/cat2.jpg
  verifyimages/cat3.jpg
  verifyimages/cat4.jpg
  verifyimages/cat5.jpg
  verifyimages/food1.jpg
  verifyimages/food2.jpg
  verifyimages/screen1.jpg
  verifyimages/screen2.jpg
Labels: enhancement

#117 Increase coverage for local repository tests
  src/main/java/dataaccess/local/LocalApplicationRepository.java
  src/main/java/dataaccess/local/LocalProjectRepository.java
  src/test/java/dataaccess/local/LocalApplicationDAOTest.java
  src/test/java/dataaccess/local/LocalProjectDAOTest.java
  src/test/java/dataaccess/local/LocalUserDAOTest.java
  src/test/java/dataaccess/local/LocalUserProjectsDAOTest.java
  src/test/java/usecase/editproject/EditProjectInteractorTest.java
  src/test/java/usecase/searchproject/SearchProjectInteractorTest.java
Labels: tests, fix

#124 Modify interactor initialization methods
  src/main/java/usecase/acceptapplication/AcceptApplicationInteractor.java
  src/main/java/usecase/acceptapplication/AcceptApplicationUseCaseFactory.java
  src/main/java/usecase/createuser/CreateUserInteractor.java
  src/main/java/usecase/createuser/CreateUserUseCaseFactory.java
  src/main/java/usecase/deleteapplication/DeleteApplicationInteractor.java
  src/main/java/usecase/deleteproject/DeleteProjectInteractor.java
  src/main/java/usecase/deleteproject/DeleteProjectUseCaseFactory.java
  src/main/java/usecase/getapplications/GetApplicationsInteractor.java
  src/main/java/usecase/getapplications/GetApplicationsUseCaseFactory.java
  src/main/java/usecase/getloggedinuser/GetLoggedInUserInteractor.java
  src/main/java/usecase/getloggedinuser/GetLoggedInUserUseCaseFactory.java
  src/main/java/usecase/getprojects/GetProjectsInteractor.java
  src/main/java/usecase/getprojects/GetProjectsUseCaseFactory.java
  src/main/java/usecase/loginuser/LoginUserInteractor.java
  src/main/java/usecase/loginuser/LoginUserUseCaseFactory.java
  src/main/java/usecase/logout/LogoutInteractor.java
  src/main/java/usecase/logout/LogoutUseCaseFactory.java
  src/main/java/usecase/rejectapplication/RejectApplicationInteractor.java
  src/main/java/usecase/rejectapplication/RejectApplicationUseCaseFactory.java
  src/main/java/usecase/searchforproject/SearchProjectUseCaseFactory.java
  src/main/java/usecase/searchforproject/SearchProjectsInteractor.java
  src/main/java/usecase/searchforuser/SearchUserInteractor.java
  src/main/java/usecase/searchforuser/SearchUserUseCaseFactory.java
  src/main/java/usecase/searchprojectbyid/SearchProjectByIdInteractor.java
  src/main/java/usecase/searchprojectbyid/SearchProjectByIdUseCaseFactory.java
  src/test/java/usecase/acceptapplication/AcceptApplicationInteractorTest.java
  src/test/java/usecase/loginuser/LoginUserInteractorTest.java
  src/test/java/usecase/rejectapplication/RejectApplicationInteractorTest.java
Labels: optimize

#121 Add tests for 3 use cases
  pom.xml
  src/main/java/usecase/deleteapplication/DeleteApplicationController.java
  src/main/java/usecase/deleteapplication/DeleteApplicationInteractor.java
  src/main/java/usecase/searchforuser/SearchUserController.java
  src/main/java/usecase/searchforuser/SearchUserInteractor.java
  src/main/java/usecase/searchprojectbyid/SearchProjectByIdController.java
  src/main/java/usecase/searchprojectbyid/SearchProjectByIdInteractor.java
  src/test/java/usecase/deleteapplication/DeleteApplicationControllerTest.java
  src/test/java/usecase/deleteapplication/DeleteApplicationInteractorTest.java
  src/test/java/usecase/deleteapplication/DeleteApplicationOutputDataTest.java
  src/test/java/usecase/deleteapplication/DeleteApplicationPresenterTest.java
  src/test/java/usecase/searchforuser/LocalUserSearchObjectTest.java
  src/test/java/usecase/searchforuser/SearchUserControllerTest.java
  src/test/java/usecase/searchforuser/SearchUserInteractorTest.java
  src/test/java/usecase/searchforuser/SearchUserPresenterTest.java
  src/test/java/usecase/searchforuser/SearchUserUseCaseFactoryTest.java
  src/test/java/usecase/searchprojectbyid/LocalProjectSearchByIdObjectTest.java
  src/test/java/usecase/searchprojectbyid/SearchProjectByIdControllerTest.java
  src/test/java/usecase/searchprojectbyid/SearchProjectByIdInteractorTest.java
  src/test/java/usecase/searchprojectbyid/SearchProjectByIdPresenterTest.java
  src/test/java/usecase/searchprojectbyid/SearchProjectByIdUseCaseFactoryTest.java
Labels: tests

#115 Added the test for GetProject
  src/main/java/usecase/manageprojects/getprojects/GetProjectsInteractor.java
  src/test/java/usecase/getprojects/GetProjectsControllerTest.java
  src/test/java/usecase/getprojects/GetProjectsInputDataTest.java
  src/test/java/usecase/getprojects/GetProjectsInteractorTest.java
  src/test/java/usecase/getprojects/GetProjectsOutputDataTest.java
  src/test/java/usecase/getprojects/GetProjectsPresenterTest.java
  src/test/java/usecase/getprojects/GetProjectsUseCaseFactoryTest.java
Labels: tests

#128 add tests for create verification use case
  src/main/java/usecase/createverification/ImageFinder.java
  src/test/java/usecase/createverification/CreateVerificationControllerTest.java
  src/test/java/usecase/createverification/CreateVerificationInteractorTest.java
  src/test/java/usecase/createverification/CreateVerificationPresenterTest.java
  src/test/java/usecase/createverification/CreateVerificationUseCaseFactoryTest.java
  src/test/java/usecase/createverification/ImageFinderTest.java
  src/test/resources/imagefindertest/noimages/notImage.txt
  src/test/resources/imagefindertest/validimages/cat1.jpg
  src/test/resources/imagefindertest/validimages/food1.jpg
Labels: tests

#129 Tests for createapplication
  src/main/java/usecase/manageapplications/createapplication/CreateApplicationController.java
  src/main/java/usecase/manageapplications/createapplication/CreateApplicationInteractor.java
  src/test/java/usecase/createapplication/CreateApplicationControllerTest.java
  src/test/java/usecase/createapplication/CreateApplicationInputBoundaryTest.java
  src/test/java/usecase/createapplication/CreateApplicationInputDataTest.java
  src/test/java/usecase/createapplication/CreateApplicationInteractorTest.java
  src/test/java/usecase/createapplication/CreateApplicationOutputDataTest.java
  src/test/java/usecase/createapplication/CreateApplicationPresenterTest.java
  src/test/java/usecase/createapplication/CreateApplicationUseCaseFactoryTest.java
Labels: tests

#131 Tests for createproject
  src/main/java/usecase/manageprojects/ManageProjectsUseCaseFactory.java
  src/main/java/usecase/manageprojects/createproject/CreateProjectInteractor.java
  src/main/java/usecase/manageprojects/createproject/CreateProjectUseCaseFactory.java
  src/test/java/usecase/createproject/CreateProjectControllerTest.java
  src/test/java/usecase/createproject/CreateProjectInputDataTest.java
  src/test/java/usecase/createproject/CreateProjectInteractorTest.java
  src/test/java/usecase/createproject/CreateProjectOutputDataTest.java
  src/test/java/usecase/createproject/CreateProjectPresenterTest.java
  src/test/java/usecase/createproject/CreateProjectUseCaseFactoryTest.java
  src/test/java/view/MyProjectsPanelTest.java
Labels: tests

#130 increase coverage for LoginUser use case
  src/main/java/usecase/loginuser/LoginUserPresenter.java
  src/test/java/usecase/loginuser/LoginUserPresenterTest.java
  src/test/java/usecase/loginuser/LoginUserUseCaseFactoryTest.java
Labels: tests

#138 Improve search project and edit project test
  src/main/java/usecase/manageprojects/editproject/EditProjectInteractor.java
  src/main/java/usecase/searchforproject/LocalProjectSearchObject.java
  src/main/java/usecase/searchforproject/SearchProjectUseCaseFactory.java
  src/main/java/usecase/searchforproject/SearchProjectsInteractor.java
  src/test/java/usecase/editproject/EditProjectInteractorTest.java
  src/test/java/usecase/editproject/EditProjectPresenterTest.java
  src/test/java/usecase/editproject/EditProjectUseCaseFactoryTest.java
  src/test/java/usecase/searchproject/SearchProjectControllerTest.java
  src/test/java/usecase/searchproject/SearchProjectInteractorTest.java
  src/test/java/usecase/searchproject/SearchProjectUseCaseFactoryTest.java
Labels: tests

#139 Remove requirement of api key and remove usage of api calls in tests
  src/main/java/api/embeddingapi/OpenAPIDataEmbed.java
  src/main/java/config/DataAccessConfig.java
  src/main/java/dataaccess/local/LocalApplicationRepository.java
  src/main/java/dataaccess/local/LocalEmbedRepository.java
  src/main/java/dataaccess/local/LocalProjectRepository.java
  src/main/java/dataaccess/local/LocalUserProjectsRepository.java
  src/main/java/dataaccess/local/LocalUserRepository.java
  src/test/java/dataaccess/local/LocalProjectDAOTest.java
Labels: tests

#141 Optimize view logic of edit project view
  src/main/java/Main.java
  src/main/java/api/texttospeechservice/TextToSpeechService.java
  src/main/java/config/SpecialSettingConfig.java
  src/main/java/view/AppLaunchSettingView.java
  src/main/java/view/EditProjectPanel.java
  src/main/java/view/MyProjectsPanel.java
  src/main/java/view/SettingsPanel.java
  src/main/java/viewmodel/EditProjectPanelViewModel.java
  src/main/java/viewmodel/LoginVerificationViewModel.java
Labels: enhancement

#143 Improve search logic
  src/main/java/usecase/searchforproject/LocalProjectSearchObject.java
  src/main/java/usecase/searchforproject/ProjectSearchInterface.java
  src/main/java/usecase/searchforproject/SearchProjectsInteractor.java
  src/main/java/view/SearchPanel.java
  src/test/java/view/EditProjectPanelTest.java
Labels: optimize

#144 increase test coverage for several use cases
  src/main/java/usecase/manageapplications/acceptapplication/AcceptApplicationInputData.java
  src/test/java/usecase/acceptapplication/AcceptApplicationPresenterTest.java
  src/test/java/usecase/acceptapplication/AcceptApplicationUseCaseFactoryTest.java
  src/test/java/usecase/logout/LogoutUseCaseFactoryTest.java
  src/test/java/usecase/rejectapplication/RejectApplicationPresenterTest.java
  src/test/java/usecase/rejectapplication/RejectApplicationUseCaseFactoryTest.java
Labels: tests

#147 Fix tag not showing up when adding projects
  src/main/java/dataaccess/local/LocalProjectRepository.java
  src/main/java/usecase/manageprojects/ManageProjectsUseCaseFactory.java
  src/main/java/usecase/manageprojects/deleteproject/DeleteProjectInteractor.java
  src/main/java/usecase/manageprojects/getprojects/GetProjectsInteractor.java
  src/main/java/usecase/searchforproject/LocalProjectSearchObject.java
  src/main/java/view/AddProjectPanel.java
  src/main/java/view/AppLaunchSettingView.java
  src/main/java/view/EditProjectPanel.java
  src/main/java/view/MyProjectsPanel.java
  src/main/java/view/components/TagPanel.java
  src/test/java/usecase/searchproject/SearchProjectInteractorTest.java
Labels: enhancement, fix

#148 Create get users test
  src/main/java/usecase/manageusers/getusers/GetUsersInteractor.java
  src/main/java/usecase/manageusers/getusers/UserData.java
  src/main/java/view/UsersPanel.java
  src/test/java/usecase/manageusers/getuser/GetUsersInteractorTest.java
  src/test/java/usecase/manageusers/getuser/GetUsersOutputDataTest.java
  src/test/java/usecase/manageusers/getuser/GetUsersPresenterTest.java
Labels: tests

#149 Add tests for get application use case
  src/main/java/usecase/manageapplications/getapplications/GetApplicationsInputData.java
  src/main/java/usecase/manageapplications/getapplications/GetApplicationsInteractor.java
  src/main/java/usecase/manageapplications/getapplications/GetApplicationsOutputData.java
  src/main/java/usecase/manageapplications/getapplications/GetApplicationsPresenter.java
  src/main/java/usecase/searchforproject/LocalProjectSearchObject.java
  src/test/java/usecase/logout/LogoutPresenterTest.java
  src/test/java/usecase/manageapplication/createapplication/CreateApplicationControllerTest.java
  src/test/java/usecase/manageapplication/createapplication/CreateApplicationInputBoundaryTest.java
  src/test/java/usecase/manageapplication/createapplication/CreateApplicationInputDataTest.java
  src/test/java/usecase/manageapplication/createapplication/CreateApplicationInteractorTest.java
  src/test/java/usecase/manageapplication/createapplication/CreateApplicationOutputDataTest.java
  src/test/java/usecase/manageapplication/createapplication/CreateApplicationPresenterTest.java
  src/test/java/usecase/manageapplication/createapplication/CreateApplicationUseCaseFactoryTest.java
  src/test/java/usecase/manageapplication/getapplication/GetApplicationInteractorTest.java
  src/test/java/usecase/manageapplication/getapplication/GetApplicationPresenterTest.java
Labels: tests

#153 fixed get user interactor test
  src/test/java/usecase/manageusers/getuser/GetUsersInteractorTest.java
Labels: fix

#152 fixed database tests
  src/main/java/config/DataAccessConfig.java
  src/main/java/dataaccess/database/manager/DatabaseConnection.java
  src/test/java/dataaccess/database/ApplicationRepositoryTest.java
  src/test/java/dataaccess/database/DatabaseHelper.java
  src/test/java/dataaccess/database/ProjectRepositoryTest.java
  src/test/java/dataaccess/database/UserProjectsRepositoryTest.java
  src/test/java/dataaccess/database/UserRepositoryTest.java
Labels: fix
